name: gemmatry
description: "A new Flutter project to demonstrate the usage of on device AI models."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # pub-dev dependencies
  flutter_gemma: ^0.9.0 # The most important dependency
  google_fonts: ^6.2.1 # Professional typography

  image_picker: ^1.0.4
  flutter_markdown: ^0.7.1
  flutter_math_fork: ^0.7.2
  url_launcher: ^6.3.1
  http: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  
  # Math solver dependencies
  google_mlkit_text_recognition: ^0.13.0  # OCR for extracting text from images
  sqflite: ^2.3.0  # Local database for history
  uuid: ^4.0.0  # Generate unique IDs for problems
  intl: ^0.19.0  # Date formatting for history
  image: ^4.1.7  # Image processing for OCR enhancement
  
  # Background processing and notifications
  flutter_local_notifications: ^17.2.2  # Local notifications
  workmanager: ^0.8.0  # Background task management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gemma.png
    # Note: Large model files (4.4GB) cannot be bundled as Flutter assets
    # due to Android build system limitations. Using alternative loading method.
